"""Idempotent seeding of the media library + SOP center from committed seed
files (generated by tools/generate_help_seed.py).

Runs at app startup. It only does work when there is nothing to seed, and the
whole thing is wrapped so a failure can never block app startup. Media bytes
are uploaded to S3 (the sops-storage bucket); SOP articles are inserted
referencing the media by slug (/media/file/<slug>), which the generator already
baked into the HTML.

The seeded content is the La Sablésienne boutique manual: brand ``sablesienne``,
department ``boutique`` (the platform's first department).
"""
import json
import os

from init_db import db

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_MANIFEST = os.path.join(ROOT, 'media', 'seed', 'manifest.json')
MEDIA_FILES_DIR = os.path.join(ROOT, 'media', 'seed', 'help')
HELP_MANIFEST = os.path.join(ROOT, 'help', 'seed', 'manifest.json')
HELP_DIR = os.path.join(ROOT, 'help', 'seed')

# The committed seed is the Sablésienne boutique manual.
SEED_BRAND = 'sablesienne'
SEED_DEPARTMENT_SLUG = 'boutique'
SEED_DEPARTMENT_NAME = 'Boutique'
SEED_DEPARTMENT_ICON = 'fa-store'


def _load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def seed_media(app):
    """Upload the committed seed images to S3 and register a MediaAsset row for
    each. Self-healing: every item is checked individually and committed on its
    own, so a previously-interrupted seed (or a missing row) is filled in on a
    later boot rather than skipped wholesale."""
    from sqlalchemy.exc import IntegrityError
    from media import storage
    from media.models import MediaAsset

    if not os.path.exists(MEDIA_MANIFEST):
        return 0
    if not storage.is_configured():
        app.logger.warning('Media seed skipped: S3 storage not configured (set OVH__* vars).')
        return 0

    items = _load_json(MEDIA_MANIFEST)
    created = 0
    for it in items:
        slug = it['slug']
        if MediaAsset.query.filter_by(slug=slug).first():
            continue
        fpath = os.path.join(MEDIA_FILES_DIR, it['filename'])
        if not os.path.exists(fpath):
            continue
        with open(fpath, 'rb') as f:
            data = f.read()
        ext = it['filename'].rsplit('.', 1)[-1]
        key = f"{storage.MEDIA_PREFIX}seed/{slug}.{ext}"
        if not storage.object_exists(key):
            storage.put_object(key, data, it.get('content_type', 'application/octet-stream'))
        db.session.add(MediaAsset(
            slug=slug, filename=it['filename'],
            content_type=it.get('content_type', 'application/octet-stream'),
            s3_key=key, size=len(data), is_seed=True,
        ))
        try:
            db.session.commit()  # per-item so one clash can't lose the batch
            created += 1
        except IntegrityError:
            db.session.rollback()  # another worker/boot already inserted it
    return created


def _ensure_seed_department(app):
    """Create the Sablésienne Boutique department if missing; return its slug."""
    from help.models import SopDepartment
    dept = SopDepartment.query.filter_by(brand=SEED_BRAND, slug=SEED_DEPARTMENT_SLUG).first()
    if not dept:
        dept = SopDepartment(brand=SEED_BRAND, slug=SEED_DEPARTMENT_SLUG,
                             name=SEED_DEPARTMENT_NAME, icon=SEED_DEPARTMENT_ICON,
                             sort_order=0)
        db.session.add(dept)
        db.session.commit()
    return dept.slug


def seed_help(app):
    from help.models import HelpArticle
    from help.search import html_to_text
    import re

    if not os.path.exists(HELP_MANIFEST):
        return 0
    if HelpArticle.query.filter_by(brand=SEED_BRAND, department=SEED_DEPARTMENT_SLUG).count() > 0:
        return 0

    dept_slug = _ensure_seed_department(app)
    items = _load_json(HELP_MANIFEST)
    created = 0
    for it in items:
        html_path = os.path.join(HELP_DIR, it['html_file'])
        body_html = ''
        if os.path.exists(html_path):
            with open(html_path, 'r', encoding='utf-8') as f:
                body_html = f.read()
        search_text = it.get('search_text') or \
            re.sub(r'\s+', ' ', f"{it['title']} {html_to_text(body_html)}").strip()
        db.session.add(HelpArticle(
            brand=SEED_BRAND, department=dept_slug,
            slug=it['slug'], title=it['title'], category=it['category'],
            body_html=body_html, search_text=search_text[:60000],
            sort_order=it.get('order', 0), is_published=True, is_seed=True,
        ))
        created += 1
    db.session.commit()
    return created


def ensure_categories(app):
    """Populate help_categories from the seeded articles' distinct categories
    (scoped to the seed brand+department) the first time it is empty."""
    from help.models import HelpArticle, HelpCategory
    if HelpCategory.query.filter_by(brand=SEED_BRAND, department=SEED_DEPARTMENT_SLUG).count() > 0:
        return 0
    rows = (db.session.query(HelpArticle.category,
                             db.func.min(HelpArticle.sort_order))
            .filter_by(brand=SEED_BRAND, department=SEED_DEPARTMENT_SLUG)
            .group_by(HelpArticle.category)
            .order_by(db.func.min(HelpArticle.sort_order)).all())
    created = 0
    for i, (name, _order) in enumerate(rows):
        if not name:
            continue
        db.session.add(HelpCategory(brand=SEED_BRAND, department=SEED_DEPARTMENT_SLUG,
                                    name=name, sort_order=i))
        created += 1
    if created:
        db.session.commit()
    return created


def ensure_default_group(app):
    """Make sure a default 'staff' group exists so admins can configure module
    access before users sign in. SOPs themselves are open to every
    authenticated user, so the default group grants no special modules."""
    from administration.models import Group
    grp = Group.query.filter_by(name='staff').first()
    if not grp:
        db.session.add(Group(name='staff', description='Utilisateurs'))
        db.session.commit()
        return 1
    return 0


def run_seed(app):
    with app.app_context():
        try:
            m = seed_media(app)
            h = seed_help(app)
            ensure_categories(app)
            ensure_default_group(app)
            if m or h:
                app.logger.info(f'Seed complete: {m} media, {h} SOP articles.')
        except Exception as e:
            db.session.rollback()
            app.logger.warning(f'Seeding skipped/failed (non-fatal): {e}')
